# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 04:22
from __future__ import unicode_literals

import blogApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator_name', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('wall_owner', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to=blogApp.models.post_upload_to)),
            ],
        ),
    ]
